name: MB Solr Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install brainz-mmd2-jaxb
        run: |
          find src/main/java -type f -print0 | xargs -0 touch
          mvn install
        working-directory: mmd-schema/brainz-mmd2-jaxb

      - name: Build with Maven
        run: mvn package
        working-directory: mb-solr
